# Generated by Django 4.1.1 on 2022-10-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0003_pedido_lineapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='Pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
